### ISSUE TITLE
Is it possible to cluster new documents without relearning everything?

### ISSUE THREAD

**Issue by CJxD** [percyliang/brown-cluster#17]
I'm looking for some way to run the clustering algorithm while using previously learned collocs, map, and paths. I tried pointing to the paths file with the `--paths` flag, but this just overwrote it with a newly learned one.

I don't have time to relearn everything from scratch: it takes days!

**Comment by jonsafari** [comment]
The Brown clustering algorithm doesn't lend itself well to this scenario.  Exchange algorithm clustering would be better suited for this, since it's iterative.  With [ClusterCat](https://github.com/jonsafari/clustercat) you can do this using the `--class-file` command-line flag.

**Comment by CJxD** [comment]
Thanks!
